name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - '**/Dockerfile'
      - 'path/to/your/docker/context/**'  # optionally watch context files
      # or just watch the whole repo: omit `paths` or customize as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile        # path to your Dockerfile if not in root, adjust accordingly
        push: true
        tags: marcosbolanos/my-dev-container-setup:latest
